server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location = /remoteEntry.json {
        add_header Access-Control-Allow-Origin * always;
        add_header Cache-Control "no-store" always;
        try_files $uri =404;
    }

    location ~* \.(js|mjs|css|json|ico|svg|png|jpg|jpeg|gif|webp)$ {
        add_header Access-Control-Allow-Origin * always;
        add_header Cache-Control "no-store" always;
        try_files $uri =404;
    }
}
